# vim ft=yaml
# travis-ci.org and coveralls definition for NeuroSynth build
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install lsb-release
  - source /etc/lsb-release
  - echo ${DISTRIB_CODENAME}
  - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
  - sudo apt-get update -qq
  - sudo apt-cache policy           # What is actually available?
  - sudo apt-get install -qq python-scipy python-nibabel
  - sudo apt-get install -qq python-pandas
  - sudo apt-get install -qq python-sklearn
  - sudo apt-get install -qq python-ply
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -q coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coverage run --rcfile=.travis_coveragerc setup.py test; else python setup.py test; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
